algoritmo "semnome"
// Função :
// Autor :
// Data : 05/09/2018
// Seção de Declarações 
var
N1,N2,Md:real
inicio
// Seção de Comandos
escreval ("Descubra se foi aprovado")
escreval ("digite a primeira nota")
leia (N1)
escreval ("digite a segunda nota")
leia (N2)
Md <- (N1+N2)/2
Se(Md>=5) entao
      escreva("O aluno alcançou a média para aprovação")
 Senao
       escreval("O aluno não alcançou a média,portanto foi reprovado")
       Fimse
fimalgoritmo
