algoritmo "semnome"
// Função :
// Autor :
// Data : 05/09/2018
// Seção de Declarações 
var
A,B :logico
X,Y :real
R,S,T :caracter
inicio
// Seção de Comandos
A<- verdadeiro
B<- falso
Y<- 5.0
X<- 2.5
R<- "José"
S<- "João"
T<- "Maria"
A ou B -> verdadeiro
(A) e (B) -> falso
não (A) -> falso
X=Y -> falso
X=(Y/2) -> verdadeiro
R=S -> falso
S=T -> falso
R<>S -> verdadeiro
R>S -> verdadeiro
S>T -> falso
((A ou B)ou(X=Y)ou(S=T) -> verdadeiro
fimalgoritmo
