algoritmo "semnome"
// Função :
// Autor :
// Data : 05/09/2018
// Seção de Declarações 
var
nu1,resultado,nu2,resultado1 :inteiro
inicio
// Seção de Comandos
escreval ("veja o sucessor e antecessor de um numero")
escreval ("digite o numero")
leia (nu1)
nu2 <- 0
resultado <- nu1-1
resultado1 <- nu2+nu1+1
escreval("O sucessor e antecessor do numero é ",resultado," e ",resultado1)
fimalgoritmo
